---
title: "About Melinda Higgins, PhD"
---

## Melinda Higgins <i class="fa fa-github fa-1x"></i> [Melinda's **Github** Repositories](https://github.com/melindahiggins2000)

[Melinda Higgins](https://melindahiggins.netlify.app/) holds dual graduate degrees in Chemometrics and Statistics. She is the author/creator of a Datacamp Course [R for SAS Users](https://www.datacamp.com/courses/r-for-sas-users) and a Coursera Course [Reproducible Templates for Analysis and Dissemination](https://www.coursera.org/learn/reproducible-templates-analysis). She is a [senior biostatistician and research professor](http://nursing.emory.edu/faculty-and-research/directory/profile.html?id=980) in the Office of Nursing Research - School of Nursing - Emory University in Atlanta, GA (2007-current). Prior to that she was a Principal Research Scientist at the Georgia Tech Research Institute (1996-2011) and Program Manager for the $17M National Guard Bureau Technology Consortium. 

She has over 24+ years experience performing and managing research in wide-ranging applications including aircraft sensor systems, remote sensing, multispectral/hyperspectral processing, signatures intelligence, knowledge decision support systems, geospatial information systems, sensors and image fusion, target recognition, bio-behavioral phenotype characterization and modeling, and statistical support for clinical trials.

### Programming and Statistical Software Expertise

* R, RStudio
* Rmarkdown
* MATLAB
* S-plus
* Pascal
* SPSS
* SAS
* SYSTAT
* FORTRAN

### Contact Information

> Melinda Higgins, PhD <br>
  Professor (research) <br>
  Nell Hodgson Woodruff School of Nursing <br>
  Emory University; Atlanta, GA
  Email: [mkhiggi@emory.edu](mailto: mkhiggi@emory.edu) <br>
  
  
